apiRules:
  - exclude:
      uidRegex: Exiled.Updater
      type: Namespace
  - exclude:
      uidRegex: Exiled.Example
      type: Namespace
  - exclude:
      uidRegex: Exiled.CreditTags
      type: Namespace
