name: Labeler

on:
  - pull_request_target

defaults:
  run:
    working-directory: ./EXILED

jobs:
  set-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Labeler
      uses: actions/labeler@v5.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml
        sync-labels: true
